[package]
name = "hattrick_packets_lib"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.146", features = ["derive"] }
serde_json = "1.0.86"
macroquad = "0.3.24"



